import{a as y,i as b,S as L}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function l(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=l(r);fetch(r.href,o)}})();async function h(t,e,l){try{return(await y.get(`https://pixabay.com/api/?key=42026920-e619b387ca2127f1aff40b8e2&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${l}`)).data}catch(n){throw console.error("Error fetching data:",n),n}}function w(t){return t.hits.map(e=>`<li class="gallery-item"><a href="${e.webformatURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
            <div class='comments'>
            <p><b>Likes: </b>${e.likes}</p>
            <p><b>Views: </b>${e.views}</p>
            <p><b>Comments: </b>${e.comments}</p>
            <p><b>Downloads: </b>${e.downloads}</p>
            </div>
            </li>`).join("")}const v=document.querySelector("#form"),a=document.querySelector(".loader"),p=document.querySelector(".gallery"),c=document.querySelector(".load-btn");let i,m=15,s="",u;const S={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};document.addEventListener("DOMContentLoaded",()=>{v.addEventListener("submit",E),c.addEventListener("click",$)});async function E(t){if(t.preventDefault(),s=document.getElementById("search").value.trim(),!s||s===" ")return f("The search field should not be empty");i=1,a.classList.remove("hidden"),c.classList.remove("hidden"),p.innerHTML="";try{const e=await h(s,i,m);g(e)}catch(e){console.error("Error fetching data:",e)}finally{a.classList.add("hidden")}}async function $(){i++,a.classList.remove("hidden");try{const t=await h(s,i,m);g(t),M(),i*m>=t.totalHits&&q()}catch(t){console.error("Error fetching data:",t)}finally{a.classList.add("hidden")}}function q(){c.classList.add("hidden"),f("We're sorry, but you've reached the end of search results.")}function M(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function f(t){b.error({title:"",backgroundColor:"#EF4040",message:t,position:"topRight"})}function g(t){if(t.hits.length===0)c.classList.add("hidden"),f("Sorry, there are no images matching your search query. Please try again!");else{const e=w(t);p.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new L(".gallery a",S)}}
//# sourceMappingURL=commonHelpers.js.map
