import{a as y,i as b,S as L}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function l(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=l(r);fetch(r.href,o)}})();async function p(e,t,l){try{return(await y.get(`https://pixabay.com/api/?key=42026920-e619b387ca2127f1aff40b8e2&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${l}`)).data}catch(s){throw console.error("Error fetching data:",s),s}}function w(e){return e.hits.map(t=>`<li class="gallery-item"><a href="${t.webformatURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}"></a>
            <div class='comments'>
            <p><b>Likes: </b>${t.likes}</p>
            <p><b>Views: </b>${t.views}</p>
            <p><b>Comments: </b>${t.comments}</p>
            <p><b>Downloads: </b>${t.downloads}</p>
            </div>
            </li>`).join("")}const v=document.querySelector("#form"),c=document.querySelector(".loader"),f=document.querySelector(".gallery"),a=document.querySelector(".load-btn");let i,m=40,n="",u;const S={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};document.addEventListener("DOMContentLoaded",()=>{v.addEventListener("submit",E),a.addEventListener("click",$)});async function E(e){if(e.preventDefault(),n=document.getElementById("search").value.trim(),!n||n===" ")return h("The search field should not be empty");i=1,c.classList.remove("hidden"),a.classList.remove("hidden"),f.innerHTML="";try{const t=await p(n,i,m);g(t)}catch(t){console.error("Error fetching data:",t)}finally{c.classList.add("hidden")}}async function $(){i++,c.classList.remove("hidden");try{const e=await p(n,i,m);g(e),M(),i*m>=e.totalHits&&q(),f.querySelectorAll(".gallery-item").length>=e.totalHits&&a.classList.add("hidden")}catch(e){console.error("Error fetching data:",e)}finally{c.classList.add("hidden")}}function q(){a.classList.add("hidden"),h("We're sorry, but you've reached the end of search results.")}function M(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function h(e){b.error({title:"",backgroundColor:"#EF4040",message:e,position:"topRight"})}function g(e){if(e.hits.length===0)a.classList.add("hidden"),h("Sorry, there are no images matching your search query. Please try again!");else{const t=w(e);f.insertAdjacentHTML("beforeend",t),u?u.refresh():u=new L(".gallery a",S)}}
//# sourceMappingURL=commonHelpers.js.map
